apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
  labels:
    app: kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
        - name: kafka-producer
          image: sharmaaakash170/kafka-producer:latest
          ports:
            - containerPort: 8080  
          env:
          - name: KAFKA_BOOTSTRAP_SERVERS
            value: "kafka-service.default.svc.cluster.local:9093"
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.json
              subPath: config.json
      volumes:
        - name: config-volume
          configMap:
            name: kafka-producer-config  # The configMap we'll create next
