apiVersion: v1
kind: Service
metadata:
  name: kafka-producer
spec:
  selector:
    app: kafka-producer
  ports:
    - protocol: TCP
      port: 8080  # Exposing the port your application is listening on
      targetPort: 8080
